# Generated by Django 2.2.3 on 2019-08-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190819_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preparationTime',
            field=models.PositiveIntegerField(),
        ),
    ]
